# Generated by Django 2.2.4 on 2019-08-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
