# Generated by Django 2.2.4 on 2019-08-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
    ]
